#!/usr/bin/env python3
from http.server import SimpleHTTPRequestHandler, HTTPServer
import argparse
import os
import sys


def run(port, bind):

    protocol = "HTTP/1.0"
    server_class = HTTPServer
    handler_class = SimpleHTTPRequestHandler

    server_address = (bind, port)

    handler_class.protocol_version = protocol
    with server_class(server_address, handler_class) as httpd:
        sa = httpd.socket.getsockname()
        serve_message = "Serving HTTP on {host} port {port} (http://{host}:{port}/) ..."
        print(serve_message.format(host=sa[0], port=sa[1]))
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\nKeyboard interrupt received, exiting.")
            sys.exit(0)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument("-p", "--port", action="store", type=int, default=5030)
    parser.add_argument("-b", "--bind", action="store", type=str, default="127.0.0.1")
    parser.add_argument("-d", "--dir", action="store", type=str, default=".")

    args = parser.parse_args()

    DIR = args.dir

    valid_path = True

    try:
        os.chdir(os.path.abspath(DIR))
    except Exception as ex:
        valid_path = False
        print(ex)

    run(port=args.port, bind=args.bind)
